### ISSUE TITLE
Missing types when trying to ingest data with Gatsby

### ISSUE THREAD

**Issue by julrich** [pristas-peter/wp-graphql-gutenberg#120]
Currently on Wordpress 5.8, wp-gatsby 1.0.11, wp-graphql 1.6.2 and wp-graphql-gutenberg 0.3.9, but still experiencing problems when trying to build the schema. Errors with the following message:

```
Missing onError handler for invocation 'building-schema', error was 'Error: Type with name "WpBlockAttributesObject" does not exists'. Stacktrace was 'Error:
 Type with name "WpBlockAttributesObject" does not exists
    at SchemaComposer.get (/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/TypeStorage.js:44:13)
    at ThunkComposer._thunk (/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/TypeMapper.js:585:34)
    at ThunkComposer.get ofType [as ofType]
(/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/ThunkComposer.js:20:34)
    at getTypeNode (/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/utils/definitionNode.js:265:28)
    at getTypeNode (/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/utils/definitionNode.js:267:21)
    at getTypeNode (/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/utils/definitionNode.js:274:21)
    at getTypeNode (/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/utils/definitionNode.js:265:12)
    at /home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/utils/definitionNode.js:317:18
    at Array.map (<anonymous>)
    at getFieldDefinitionNodes
(/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/utils/definitionNode.js:315:21)
    at getObjectTypeDefinitionNode
(/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/utils/definitionNode.js:40:13)
    at ObjectTypeComposer.getType
(/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/ObjectTypeComposer.js:700:76)
    at getGraphQLType (/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/utils/typeHelpers.js:164:17)
    at /home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/SchemaComposer.js:167:79
    at Array.forEach (<anonymous>)
    at SchemaComposer.buildSchema (/home/julrich/Projects/Frontend/code/gatsby-theme-kickstartds/node_modules/graphql-compose/lib/SchemaComposer.js:166:31)'
```

Block registry was updated right before starting Gatsby.

**Comment by ibjorn** [comment]
I'm getting the same.

WP 5.8
WPGatsby 1.0.11
WPGraphQL 1.6.3
WP GraphQL Gutenberg - Isses started after updating from 0.3.8, tried 0.3.9 and 0.3.10 (note, version number wasn't updated from .3.9 to .3.10 in plugin.php)

`Missing onError handler for invocation 'building-schema', error was 'Error: Type with name        
"WpBlockAttributesObject" does not exists'. Stacktrace was 'Error: Type with name
"WpBlockAttributesObject" does not exists
    at SchemaComposer.get
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\TypeStorage.js:44:13)
    at ThunkComposer._thunk
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\TypeMapper.js:585:34)
    at ThunkComposer.get ofType [as ofType]
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\ThunkComposer.js:20:34)
    at getTypeNode
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\utils\definitionNode.js:265:28) 
    at getTypeNode
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\utils\definitionNode.js:267:21) 
    at getTypeNode
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\utils\definitionNode.js:274:21) 
    at getTypeNode
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\utils\definitionNode.js:265:12) 
    at
C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\utils\definitionNode.js:317:18   
    at Array.map (<anonymous>)
    at getFieldDefinitionNodes
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\utils\definitionNode.js:315:21) 
    at getObjectTypeDefinitionNode
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\utils\definitionNode.js:40:13)  
    at ObjectTypeComposer.getType
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\ObjectTypeComposer.js:700:76)   
    at getGraphQLType
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\utils\typeHelpers.js:164:17)    
    at C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\SchemaComposer.js:167:79  
    at Array.forEach (<anonymous>)
    at SchemaComposer.buildSchema
(C:\Users\bjorn\www\blackalscoza\node_modules\graphql-compose\lib\SchemaComposer.js:166:31)' `

I noticed something that might help shed some light.

The above is while running `gatsby develop` on local, after updating all NPM packages.

My production version, pre-NPM update, also failed to build after updating WP GraphQL Gutenberg. However, after rolling back to 0.3.8, production works again, just local not working.

Relevant NPM packages working in production with version 0.3.8:

`"gatsby": "^3.10.1",
"gatsby-plugin-image": "^1.10.1",
"gatsby-source-filesystem": "^3.10.0",
"gatsby-source-wordpress": "^5.10.0",
"gatsby-transformer-sharp": "^3.10.0"`

Post NPM update, resulting in above error in development with all of 0.3.8, 0.3.9 and 0.3.10:

`"gatsby": "^3.11.1",
"gatsby-plugin-image": "^1.11.0",
"gatsby-source-filesystem": "^3.11.0",
"gatsby-source-wordpress": "^5.11.0",
"gatsby-transformer-sharp": "^3.11.0"`

I don't use ACF, or anything similar WP side, however, I have a few post types and blocks of my own in use.

**Comment by ibjorn** [comment]
I managed to fix this by applying [this hack](https://github.com/wp-graphql/wp-graphql/issues/1460#issuecomment-742235504).

This might be an old issue that's come back #70 

Currently working for me in development and production:

//wp
WP 5.8
WPGatsby 1.0.11
WPGraphQL 1.6.3
WP GraphQL Gutenberg 0.3.11

//gatsby
gatsby 3.10.1
gatsby-source-wordpress 5.11.0

**Comment by julrich** [comment]
Interesting, will have a look at your hack, thanks!

**Comment by robclancy** [comment]
I'm also using the hack and only installed today so on latest version.
