### ISSUE TITLE
Fatal error: Uncaught WPGraphQLGutenberg\Blocks\RegistryNotSourcedException: Client side block registry is missing. You need to open up gutenberg or load it from WPGraphQLGutenberg Admin page.

### ISSUE THREAD

**Issue by jakubszynklarz** [pristas-peter/wp-graphql-gutenberg#130]
Hello, after installing the latest version of the wp graphql gutenberg plugin, an error occurred below - after disabling the plugin, the error disappears.

`Fatal error: Uncaught WPGraphQLGutenberg\Blocks\RegistryNotSourcedException: Client side block registry is missing. You need to open up gutenberg or load it from WPGraphQLGutenberg Admin page. in /usr/home/indigital/domains/webninjas.indigital.guru/public_html/wp-content/plugins/wp-graphql-gutenberg-0.3.11/src/Blocks/Registry.php:41 Stack trace: #0 /usr/home/indigital/domains/webninjas.indigital.guru/public_html/wp-content/plugins/wp-graphql-gutenberg-0.3.11/src/Schema/Types/BlockTypes.php(263): WPGraphQLGutenberg\Blocks\Registry::get_registry() #1 /usr/home/indigital/domains/webninjas.indigital.guru/public_html/wp-includes/class-wp-hook.php(303): WPGraphQLGutenberg\Schema\Types\BlockTypes->WPGraphQLGutenberg\Schema\Types\{closure}(Object(WPGraphQL\Registry\TypeRegistry)) #2 /usr/home/indigital/domains/webninjas.indigital.guru/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #3 /usr/home/indigital/domains/webninjas.indigital.guru/public_html/wp-includes/plugin.php(470): WP_Hook->do_actio in /usr/home/indigital/domains/webninjas.indigital.guru/public_html/wp-content/plugins/wp-graphql-gutenberg-0.3.11/src/Blocks/Registry.php on line 41`

PHP 7.3.31
WP 5.8.2

PLUGINS:

ACF PRO 5.10.2
WP GATSBY 1.1.4
WP GRAPHQL 1.6.7
WP GRAPHQL Gutenberg 0.3.11
Yoast SEO 17.7
Add WPGraphQL SEO 4.16.0
WPGraphQL for Advanced Custom Fields 0.5.2

Does anyone know what is the cause of the error?

**Comment by jakubszynklarz** [comment]
@pristas-peter @jasonbahl are you able to help solve the problem?

**Comment by pristas-peter** [comment]
Client side block registry is missing. You need to open up gutenberg or load it from WPGraphQLGutenberg Admin page.

**Comment by jakubszynklarz** [comment]
@pristas-peter There is no such possibility, an error occurs.

![error](https://user-images.githubusercontent.com/37659619/145215705-5275ae39-a30c-4444-8230-49a0fc338ca7.png)

**Comment by jakubszynklarz** [comment]
@pristas-peter  @jasonbahl are you able to help solve the problem?

**Comment by jasonbahl** [comment]
@jakubszynklarz Can you try with only WPGraphQL and WPGraphQL for Gutenberg active? 

If it's still failing, can you confirm that you have any public post types that are using Gutenberg? And no plugins/code snippets that are disabling the block editor?

If it succeeds with only WPGraphQL + WPGraphQL for Gutenberg, I'd suggest activating the other plugins one at a time and updating the block registry to see which plugin might be causing a conflict. 

For what it's worth, I didn't experience this issue with just WPGraphQL and WPGraphQL for Gutenberg active.

**Comment by jakubszynklarz** [comment]
@jasonbahl Unfortunately, despite disabling all plugins and leaving WpGraphql and GraphQL Gutenberg enabled, I still get the same error

**Comment by williamegomezo** [comment]
Any update on this? Getting same error when run this plugin on docker image

**Comment by steinbergh** [comment]
I Have Gutenberg restricted to all but one custom post type (im using ACF everywhere else) would this be causing this issue cause ive run into this as well

**Comment by jakubszynklarz** [comment]
@pristas-peter, @jasonbahl Will you suggest a solution?

**Comment by jakubszynklarz** [comment]
@pristas-peter @jasonbahl I managed to register the blocks, but the error below still occurs

`Fatal error: Uncaught WPGraphQLGutenberg\Blocks\RegistryNotSourcedException: Client side block registry is missing. You need to open up gutenberg or load it from WPGraphQLGutenberg Admin page. in /usr/home/*****/domains/*****/public_html/wp-content/plugins/wp-graphql-gutenberg-0.3.11/src/Blocks/Registry.php:41 Stack trace: #0 /usr/home/*****/domains/*****/public_html/wp-content/plugins/wp-graphql-gutenberg-0.3.11/src/Schema/Types/BlockTypes.php(263): WPGraphQLGutenberg\Blocks\Registry::get_registry() #1 /usr/home/*****/domains/*****/public_html/wp-includes/class-wp-hook.php(303): WPGraphQLGutenberg\Schema\Types\BlockTypes->WPGraphQLGutenberg\Schema\Types\{closure}(Object(WPGraphQL\Registry\TypeRegistry)) #2 /usr/home/*****/domains/*****/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #3 /usr/home/*****/domains/*****/public_html/wp-includes/plugin.php(470): WP_Hook->do_actio in /usr/home/*****/domains/*****/public_html/wp-content/plugins/wp-graphql-gutenberg-0.3.11/src/Blocks/Registry.php on line 41`

**Comment by codedbyglenden** [comment]
I know this is a really old ticket. But for anyone running into this, I fixed it by enabling rest on a post-type, and visiting the post-new.php file for that post-type. For example with the page post type this would be: 

`${your-domain}/wp-admin/post-new.php?post_type=page`

You only need to visit it once & the error will be gone.
