### ISSUE TITLE
NO SCHEMA AVAILABLE in GraphQL IDE

### ISSUE THREAD

**Issue by LarsEjaas** [pristas-peter/wp-graphql-gutenberg#135]
I get the error:
`NO SCHEMA AVAILABLE` in the left side of the GraphQL IDE if I activate the wp-graphql-gutenberg plugin in WordPress. Are there any known issues or incompatibilities here I need to be aware of? I have updated all plugins to the recent version.

**Comment by ojohnny** [comment]
@LarsEjaas I believe that you may have to go to "GraphQL Gutenberg" in the admin panel and press the "Update block registry" button.

I think I see the same thing on a fresh WordPress install.  Not sure if there is another fix for it than manually updating the block registry.

**Comment by BenBuergelSplash** [comment]
Also getting this error when GraphQL Gutenberg is installed. This error is thrown in the browser console on the GraphiQL IDE:
```
Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: { status: 500 }.
    at r (devAssert.mjs:5:11)
    at m (buildClientSchema.mjs:27:74)
    at App.js:181:39
```

**Comment by masis-dk** [comment]
Same issue here, I am getting an error 500 :
`https://URL/index.php?graphql 500 (Internal Server Error)`

After install the plugin, clicked on `update block registry`, and then navigate ton GraphiQL IDE
I installed v0.3.12, but it show v0.3.11 in wordpress back-office

**Comment by xkibax** [comment]
Same problem here, did anyone find a solutions?
The code was fine 2 days ago and suddenly stops working.
