### ISSUE TITLE
API stopped working: Cannot use object of type GraphQL\Type\SchemaConfig as array

### ISSUE THREAD

**Issue by webartistse** [pristas-peter/wp-graphql-gutenberg#145]
After updated WP GraphQL the api stopped working. The problem seems to be that the Config now is an object so it cannot use typeLoader from config.

**Wordpress:** 5.9.2
**WP GraphQL:** 1.8.0
**WP GraphQL Gutenberg:** 0.3.4

PHP Fatal error:  Uncaught Error: Cannot use object of type GraphQL\Type\SchemaConfig as array in /Users/jax/Sites/web-cms/wordpress/wp-content/plugins/wp-graphql-gutenberg/src/Schema/Types/BlockTypes.php:248
Stack trace:
#0 /Users/jax/Sites/web-cms/wordpress/wp-includes/class-wp-hook.php(309): WPGraphQLGutenberg\Schema\Types\BlockTypes->WPGraphQLGutenberg\Schema\Types\{closure}(Object(GraphQL\Type\SchemaConfig))
#1 /Users/jax/Sites/web-cms/wordpress/wp-includes/plugin.php(189): WP_Hook->apply_filters(Object(GraphQL\Type\SchemaConfig), Array)
#2 /Users/jax/Sites/web-cms/wordpress/wp-content/plugins/wp-graphql/src/WPSchema.php(51): apply_filters('graphql_schema_...', Object(GraphQL\Type\SchemaConfig), Object(WPGraphQL\Registry\TypeRegistry))
#3 /Users/jax/Sites/web-cms/wordpress/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry.php(51): WPGraphQL\WPSchema->__construct(Object(GraphQL\Type\SchemaConfig), Object(WPGraphQL\Registry\TypeRegistry))
#4 /Users/jax/Sites/gym in /Users/jax/Sites/web-cms/wordpress/wp-content/plugins/wp-graphql-gutenberg/src/Schema/Types/BlockTypes.php on line 248

```
add_filter(
  'graphql_schema_config',
  function ($config) use ($type_names, &$type_registry) {
    $types = [$type_registry->get_type('Block')];

    foreach ($type_names as $type_name) {
      **$types[] = $config['typeLoader']($type_name);**
    }

    $config['types'] = array_merge($config['types'] ?? [], $types);
    return $config;
  },
  10
);
```

**Comment by webartistse** [comment]
I discovered that this is fixed in v0.3.11 and Wordpress did not update the plugin through the platform.
